import csv
import re

file_path = r'c:\Users\mehdi\OneDrive\Bureau\Flutter\cardly\assets\tempo\english_french.csv'

# Dictionary for filling missing English translations
translations = {
    "responsable / redevable": "accountable",
    "comptabilité": "accounting",
    "additionner": "to add up",
    "à l'étranger": "abroad",
    "devant / en avance / à venir": "ahead",
    "climatiseur": "air conditioner",
    "porte-avions": "aircraft carrier",
    "prétendument": "allegedly",
    "amande": "almond",
    "aux côtés de": "alongside",
    "tout à fait / complétement": "altogether",
    "de toute façon": "anyway",
    "appareils électroménagers": "appliances",
    "rendez-vous": "appointment",
    "nomination du chef": "appointment",
    "inquiet": "anxious",
    "évaluation": "assessment",
    "évaluateur": "assessor",
    "actif": "asset",
    "participant": "attendee",
    "avocat": "attorney",
    "conscience": "awareness",
    "contrecoup": "backlash",
    "boulangerie": "bakery",
    "bicarbonate de soude": "baking soda",
    "se déchaîner": "to bail",
    "faillite": "bankruptcy",
    "à peine": "barely",
    "négociation": "bargaining",
    "monnaie d'agrément": "bargaining chip",
    "ventre": "belly",
    "enchérir": "to bid",
    "facture": "bill",
    "panneau d'affichage": "billboard",
    "saignement": "bleeding",
    "mixeur": "blender",
    "angles morts": "blind spots",
    "floraison": "bloom",
    "fleur": "blossom",
    "ventilateur / soufleur": "blower",
    "réservation": "booking",
    "l'ennui": "boredom",
    "rocher": "boulder",
    "limite / frontière": "boundary",
    "rompre": "to break",
    "race": "breed",
    "mariée": "bride",
    "bord": "brink",
    "large": "broad",
    "plus large": "broader",
    "meurtri": "bruised",
    "pare-balles / blindé": "bulletproof",
    "bosse": "bump",
    "fardeau": "burden",
    "en plein essor": "burgeoning",
    "boucher": "butcher",
    "mots à la mode": "buzzwords",
    "complicité": "complicity",
    "effectuer / mener / réaliser": "to carry out",
    "piège": "trap", 
    "fourre-tout / receveur": "catch-all",
    "chenille": "caterpillar",
    "plafond": "ceiling",
    "craie": "chalk",
    "applaudissement": "cheering",
    "ringard": "cheesy",
    "cerise": "cherry",
    "corvée": "chore",
    "idiot": "chump",
    "tronçon": "chunk",
    "parpaing": "cinder block",
    "falaise": "cliff",
    "camouflage": "camouflage",
    "dans le sens des aiguilles d'une montre": "clockwise",
    "placard": "closet",
    "maladroit": "clumsy",
    "cercueil": "coffin",
    "rouage": "cog",
    "passoire": "colander",
    "être utile": "to come in handy",
    "à la veille de l'échéance": "coming due",
    "engagement": "commitment",
    "conformité": "compliance",
    "commodité": "convenience",
    "pratique": "handy", 
    "cadavre": "corpse",
    "chalet": "cottage",
    "compte sur moi": "count on me",
    "biscuit": "cookie",
    "grue": "crane",
    "caisse": "crate",
    "informations d'identification": "credentials",
    "foule": "crowd",
    "câlin": "cuddle",
    "signal": "cue",
    "allumez les lumières": "cue the lights",
    "armoire": "cupboard",
    "accolades": "curly brackets",
    "malédiction": "curse",
    "rideaux": "curtains",
    "quotidiennement": "daily",
    "sourd": "deaf",
    "pont": "deck",
    "cerf": "deer",
    "défaut": "defect",
    "livraison / prestation": "delivery",
    "abandonné": "derelict",
    "malgré": "despite",
    "agenda": "diary",
    "déterrer": "to dig up",
    "mécontent": "disgruntled",
    "disposition": "disposal",
    "poupée": "doll",
    "en aval": "downstream",
    "vidange": "drain",
    "perceuse": "drill",
    "approfondir": "to drill down",
    "ruban adhésif": "duct tape",
    "cabas": "duffel bag",
    "terne": "dull",
    "aisance": "ease",
    "écoute clandestine": "eavesdropping",
    "âgé": "elderly",
    "enceinte / boitier": "enclosure",
    "approbation": "endorsement",
    "floraison éternelle": "everlasting bloom",
    "épuisé": "exhausted",
    "installations / équipement": "facilities",
    "tourné vers le haut": "face up",
    "déguisement": "disguise",
    "restaurant chic": "fine dining",
    "adieu": "farewell",
    "démon": "demon",
    "comprendre / trouver": "to figure out",
    "rempli à ras bord": "filled to the brim",
    "trouver / savoir": "to find out",
    "sidéré": "flabbergasted",
    "côté opposé": "flip side",
    "inondation": "flood",
    "disquette": "floppy disk",
    "duveteux": "fluffy",
    "agité": "flustered",
    "ennemi": "foe",
    "interdit": "forbidden",
    "prévision": "forecast",
    "avant toute chose": "first and foremost",
    "criminalistique": "forensics",
    "science médico-légale": "forensic science",
    "contrefaçon": "forgery",
    "ancien": "former",
    "en avant": "forward",
    "source": "source",
    "flippant": "freaky",
    "effrayé": "frightened",
    "futile": "futile",
    "entonnoir": "funnel",
    "patron / chef / boss": "gaffer",
    "rassemblement": "gathering",
    "véritablement": "genuinely",
    "authentique": "genuine",
    "monter": "to go up",
    "se débarrasser": "to get rid of",
    "rire": "to giggle",
    "ver luisant": "glow worm",
    "raisin": "grape",
    "épicerie": "grocery",
    "coupable": "guilty",
    "couloir": "hallway",
    "passer la commande": "to hand over controls",
    "remettre": "to hand over",
    "poignée": "handle", 
    "polycopié": "handout",
    "gaines": "gains",
    "gueule de bois": "hangover",
    "endurci": "hardened",
    "inoffensif": "harmless",
    "gros titres": "headlines",
    "quartier général": "headquarters",
    "braquage": "heist",
    "détenu": "detainee",
    "hémorragie": "hemorrhage",
    "chanvre": "hemp",
    "par conséquent": "hence",
    "rétrospective": "hindsight",
    "indice": "hint",
    "brancher": "to hook up",
    "obstacle": "hurdle",
    "argent pour se taire": "hush money",
    "j'ai pris ma décision": "I made up my mind",
    "j'ai perdu mon sang-froid": "I lost my temper",
    "de mauvaise humeur": "ill-humored",
    "de mauvaise intention": "ill-intentioned",
    "je t'en supplie": "I beg you",
    "avec le recul": "in hindsight",
    "entrant": "incoming",
    "incitation": "incentive",
    "titulaire": "incumbent",
    "aperçu": "insight",
    "destiné": "intended",
    "il fait vraiment froid": "it's freezing",
    "soulever": "to jack up",
    "abruti": "jerk",
    "saccadé": "jerky",
    "mélanger": "to jumble",
    "confus": "confused",
    "ordure": "junk",
    "casse": "junkyard",
    "frappe de touche": "keystroke",
    "bouton / poignée": "knob",
    "retardataires": "laggards",
    "propriétaire": "landlord",
    "repère": "landmark",
    "voie": "lane",
    "genoux": "knees",
    "effet de levier": "leverage",
    "licencier": "to lay off",
    "escale / halte": "layover",
    "fuite": "leak",
    "registre": "ledger",
    "couvercle": "lid",
    "probabilité / vraisemblance": "likelihood",
    "de même": "likewise",
    "persistant": "lingering",
    "sucette": "lollipop",
    "faire attention": "to look out",
    "fou": "loony",
    "échappatoire": "loophole",
    "confortable": "comfy",
    "grumeleux": "lumpy",
    "manoir": "manor",
    "marbre": "marble",
    "matelas": "mattress",
    "moyen d'appel d'offres": "means of tender",
    "simplement": "simply",
    "sirène": "mermaid",
    "mêle toi de tes affaires": "mind your own business",
    "induit en erreur": "misled",
    "surveillance": "surveillance",
    "moine": "monk",
    "hypothèque": "mortgage",
    "paillis": "mulch",
    "banal": "mundane",
    "sieste": "nap",
    "échappé de justesse": "narrow escape",
    "néanmoins": "nevertheless",
    "sans jeu de mot": "no pun intended",
    "serment": "oath",
    "odieux": "obnoxious",
    "débarquement": "offloading",
    "délinquant": "offender",
    "pommade": "ointment",
    "démodé": "old fashioned",
    "au nom de": "on behalf of",
    "sur le plateau": "on set",
    "sur site": "on site",
    "se retirer": "to opt out",
    "autruche": "ostrich",
    "en faillite": "bankrupt",
    "hors service": "out of order",
    "panne": "outage",
    "épidémie": "outbreak",
    "banni": "banished",
    "contour": "outline",
    "externalisation": "outsourcing",
    "exceptionnel": "outstanding",
    "du jour au lendemain": "overnight",
    "accablant / écrasant": "overwhelming",
    "copain": "pal",
    "s'est évanoui": "passed out",
    "chèque de paie": "paycheck",
    "gains": "gains",
    "paie": "pay",
    "poire": "pear",
    "piéton": "pedestrian",
    "jeter un œil dehors": "to peek out",
    "centime": "penny",
    "animal de compagnie": "pet",
    "hameçonnage": "phishing",
    "oreiller": "pillow",
    "énervé": "pissed off",
    "fosse": "pit",
    "texte brut": "plain text",
    "s'est laissé tomber": "to plop down",
    "en chute libre": "plummeting",
    "étang / bassin / mare": "pond",
    "crevette": "prawn",
    "locaux": "premises",
    "à peu près": "pretty much",
    "preuve": "proof",
    "retirer / enlever / réussir": "to pull off",
    "se moquer de quelqu'un": "to pull someone's leg",
    "marionnettes": "puppets",
    "chiot": "puppy",
    "sac à main": "purse",
    "requête": "query",
    "étagère": "rack",
    "imperméable": "raincoat",
    "accélerer / montée en puissance": "to ramp up",
    "viol": "rape",
    "préparation": "preparation",
    "royaume": "realm",
    "indépendamment": "independently",
    "régulièrement": "regularly",
    "rajeunissant": "rejuvenating",
    "rechute": "relapse",
    "pertinent": "relevant",
    "répulsif": "repellent",
    "vente au détail": "retail",
    "vénéré": "revered",
    "tournant": "turning point",
    "devinette": "riddle",
    "truqué": "rigged",
    "truquage": "rigging",
    "tout de suite": "right away",
    "émeute": "riot",
    "voyou": "rogue",
    "retrousses tes manches": "roll up your sleeves",
    "rouleaux": "rolls",
    "corde": "rope",
    "peste / pourriture": "rot",
    "vagabond": "vagabond",
    "caoutchouc": "rubber",
    "tapis": "rug",
    "à court d'argent": "running low on cash",
    "qui coule": "running",
    "rouillé": "rusty",
    "impitoyable": "ruthless",
    "coffre-fort": "safe",
    "santé mentale": "sanity",
    "balance": "scale",
    "dispersion": "scatter",
    "feraille": "scrap",
    "dépistage": "screening",
    "bousiller": "to screw up",
    "tournevis": "screwdriver",
    "foutu": "screwed",
    "dégeulasse": "disgusting",
    "marin": "sailor",
    "sans coupure / continue / permanent": "seamless",
    "sans égal": "second to none",
    "crise": "crisis",
    "rarement": "rarely",
    "louche": "shady",
    "chérie": "sweetheart",
    "hangar": "shed",
    "pur": "pure",
    "abri": "shelter",
    "changement": "change",
    "sténographie / abrégé": "shorthand",
    "vue": "sight",
    "à lui seul": "single-handedly",
    "gorgée": "sip",
    "gratte-ciel": "skyscraper",
    "lisse": "smooth",
    "détective": "detective",
    "léger": "light",
    "légèrement": "slightly",
    "lance-pierres": "slingshot",
    "pente": "slope",
    "claquement": "snap",
    "fermer brusquement": "to snap shut",
    "acheté / vendu rapidement": "snapped up",
    "instantané": "snapshot",
    "ronflement": "snoring",
    "trempé": "soaked",
    "détrempé": "soggy",
    "seul": "alone",
    "uniquement": "only",
    "mal de gorge": "sore throat",
    "de rechange": "spare",
    "fer de lance": "spearhead",
    "broche": "brooch",
    "usurpé": "spoofed",
    "usurpation d'identité": "spoofing",
    "cran": "guts",
    "crochets": "brackets",
    "mise en scène": "staging",
    "parties prenantes": "stakeholders",
    "commencer fort": "to start strong",
    "garder une longueur d'avance": "to stay ahead",
    "vapeur": "steam",
    "raide": "stiff",
    "points de suture": "stitches",
    "s'est arrêté": "stopped",
    "poêle": "stove",
    "cuisinière": "cooker",
    "direct": "direct",
    "échoué": "failed",
    "étirement": "stretching",
    "robuste": "robust",
    "sommet": "summit",
    "fournisseur": "supplier",
    "chaîne d'approvisionnement": "supply chain",
    "rendu": "rendered",
    "enquête": "inquiry",
    "programme": "program",
    "onglet": "tab",
    "adaptation": "adaptation",
    "passer à l'action": "to take action",
    "prendre le control": "to take control",
    "salaire net": "net salary",
    "cône": "cone",
    "appel d'offres": "tender",
    "c'est exactement ce qu'il me fallait": "that's exactly what I needed",
    "c'était génial": "it was great",
    "ce n'est pas la question": "that's not the point",
    "le soleil s'est levé": "the sun rose",
    "épais": "thick",
    "cuisse": "thigh",
    "assoiffé": "thirsty",
    "menaçant": "threatening",
    "seuil": "threshold",
    "gorge": "throat",
    "vignette": "thumbnail",
    "ainsi": "thus",
    "marée": "tide",
    "serré": "tight",
    "inclinaison": "tilt",
    "en temps opportun": "timely",
    "minuscule": "tiny",
    "basculer": "to switch",
    "fatigué": "tired",
    "permettre": "to allow",
    "surgir": "to arise",
    "assister à": "to attend",
    "cuire": "to bake",
    "supplier / implorer": "to beg",
    "plier": "to fold",
    "fleurir": "to bloom",
    "déranger": "to disturb",
    "se conformer": "to comply",
    "faire face": "to face",
    "faire un câlin": "to hug",
    "pendre": "to hang",
    "tromper": "to cheat",
    "rendre illisible": "to make illegible",
    "renoncer": "to give up",
    "creuser": "to dig",
    "plonger": "to dive",
    "divulger": "to disclose",
    "dissiper": "to dispel",
    "noyer": "to drown",
    "jeter / déverser": "to dump",
    "intégrer": "to integrate",
    "détourner": "to divert",
    "englober": "to encompass",
    "engloutir": "to swallow",
    "exposer": "to expose",
    "effacer": "to erase",
    "couler": "to flow",
    "rassembler": "to gather",
    "glacer": "to freeze",
    "saluer": "to greet",
    "accrocher": "to hang",
    "traîner": "to drag",
    "embaucher": "to hire",
    "flotter": "to float",
    "se faire passer pour": "to pretend to be",
    "accuser": "to accuse",
    "s'entremêler": "to intermingle",
    "compromettre": "to compromise",
    "secouer / tirer brusquement": "to jerk",
    "porter malheur": "to bring bad luck",
    "noter": "to note",
    "louer": "to rent",
    "tirer parti / exploiter": "to exploit",
    "faire fondre": "to melt",
    "engrainer": "to engage",
    "se mêler": "to meddle",
    "atténuer": "to mitigate",
    "grignoter": "to nibble",
    "chevaucher": "to straddle",
    "dépasser": "to overtake",
    "submerger": "to submerge",
    "identifier": "to identify",
    "s'effondrer": "to collapse",
    "riposter": "to retaliate",
    "récupérer": "to recover",
    "déchirer": "to tear",
    "frotter": "to rub",
    "brouiller / se démener": "to scramble",
    "scruter / examiner minutieusement": "to scrutinize",
    "rompre": "to break",
    "raser": "to shave",
    "mettre de côté / suspendre": "to put aside",
    "siroter": "to sip",
    "monter en flèche": "to soar",
    "calomnier": "to slander",
    "casser / rompre": "to break",
    "gribouiller": "to scribble",
    "miser": "to bet",
    "puer": "to stink",
    "rationaliser": "to rationalize",
    "aspirer": "to aspire",
    "poursuivre en justice": "to sue",
    "transpirer": "to sweat",
    "s'attaquer": "to attack",
    "tailler / adapter": "to tailor",
    "étrangler / limiter / asphyxier": "to strangle",
    "chatouiller": "to tickle",
    "attacher": "to tie",
    "donner un pourboire": "to tip",
    "se dérouler": "to unfold",
    "détacher": "to detach",
    "fouetter": "to whip",
    "chuchoter": "to whisper",
    "retirer": "to withdraw",
    "résister": "to resist",
    "dentifrice": "toothpaste",
    "difficile": "difficult",
    "réfléchi": "thoughtful",
    "serviette": "towel",
    "tapis roulant": "treadmill",
    "randonnée": "hike",
    "dépannage": "troubleshooting",
    "inventé de toutes pièces": "fabricated",
    "tir à la corde": "tug of war",
    "gazon": "lawn",
    "moche": "ugly",
    "sous-vêtements": "underwear",
    "syndicat": "union",
    "bouleversé": "upset",
    "crispé": "tense",
    "subordonné": "subordinate",
    "chambre forte": "vault",
    "polyvalent": "versatile",
    "acquisition": "acquisition",
    "coupon": "coupon",
    "farfelu": "wacky",
    "liasse": "bundle",
    "salaire": "salary",
    "serveuse": "waitress",
    "errant": "wavering",
    "salle": "room",
    "garde-robe": "wardrobe",
    "édulcorer / atténuer": "to water down",
    "richesse": "wealth",
    "éliminer": "to eliminate",
    "pourquoi / à quoi ça sert": "what for",
    "brouette": "wheelbarrow",
    "tandis que": "while",
    "capricieux": "capricious",
    "gémissements": "moans",
    "se plainde de": "to complain about",
    "retrait": "withdrawal",
    "volontairement": "voluntarily",
    "clin d'œil": "wink",
    "virement bancaire": "bank transfer",
    "témoin": "witness",
    "pire encore": "worse",
    "blessure": "injury",
    "blessé": "injured",
    "clé": "key",
    "poignet": "wrist",
    "coup sec": "sharp blow"
}

def determine_label(english_text):
    english_text = english_text.lower().strip()
    words = english_text.split()
    
    # Verbs
    if english_text.startswith("to "):
        return "verb"
    
    # Adjectives via suffixes
    adj_suffixes = ('able', 'ous', 'ive', 'ful', 'less', 'ic', 'al', 'ent', 'ant', 'ary', 'ory')
    if English_text.split()[0].endswith(adj_suffixes) if len(words) == 1 else False:
         return "adjective"
    
    # Specific adjective words to catch
    adj_list = ["afraid", "upset", "shady", "stiff", "tight", "thick", "tiny", "tired", "wacky", "versatile", "tough", "thoughtful", "straightforward", "stranded", "sturdy", "soaked", "soggy", "sole", "sleek", "slight", "shady", "ruthless", "rusty", "revered", "relevant", "repellent", "rigged", "pissed off", "obnoxious", "old fashioned", "outstanding", "overwhelming", "midday", "misled", "mundane", "loose", "lumpy", "likelihood", "likewise", "jumbled", "confused", "jerky", "ill-humored", "ill-intentioned", "hardened", "harmless", "guilty", "genuinely", "genuine", "freaky", "frightened", "futile", "flabbergasted", "fluffy", "flustered", "forbidden", "former", "exhausted", "disgruntled", "dull", "disgusting", "derelict", "deaf", "daily", "convenient", "comfy", "clumsy", "cheesy", "bruised", "bulletproof", "burgeoning", "barely", "bankrupt", "anxious", "accountable", "ahead", "allegedly", "altogether", "anyway"]
    
    if english_text in adj_list:
        return "adjective"   

    # Idioms (phrases, questions)
    if "?" in english_text or len(words) >= 3:
        return "idiom"
        
    # Adverbs
    if english_text.endswith("ly"):
        return "adjective" # Actually usually adverb, but user only gave noun, verb, adjective, idiom choices. Adverbs fall under adjective broadly or 'idiom' if phrase? Or maybe just 'adjective' incorrectly but closely enough. Or I should add 'adverb' if it was valid, but user limited choice. I'll use 'adjective' (modifier).
    
    return "noun"

rows = []
with open(file_path, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    for row in reader:
        # Fill missing English
        if not row['english'] or not row['english'].strip():
            french_clean = row['french'].strip()
            if french_clean in translations:
                row['english'] = translations[french_clean]
        
        # Correction of hint logic for newly added rows
        if not row['frontHint']:
            # Assume pattern: commence par {first_letter_of_french}
            if row['french']:
                row['frontHint'] = f"commence par {row['french'][0].lower()}"
        
        if not row['backHint']:
             if row['english']:
                 row['backHint'] = f"starts with {row['english'][0].lower()}"

        # Recalculate label
        if row['english']:
            row['label'] = determine_label(row['english'])
            
        rows.append(row)

# Write back
with open(file_path, 'w', encoding='utf-8', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print(f"Processed {len(rows)} rows.")
